# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-12 15:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20171102_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 12, 15, 13, 19, 574750, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
